### ISSUE TITLE
Arbiter Error (ComputationGraphTaskCreator.java:113)

### ISSUE THREAD

**Issue by rmeex07** [deeplearning4j/Arbiter#116]
#### Issue Description

I think its bug or something wrong here at ComputationGraphTaskCreator.java:113
DataSetIterator dataSetIterator = ScoreUtil.getIterator(dataProvider.trainData(candidate.getDataParameters()));

Please describe your issue, along with:
- expected behavior
- encountered behavior

Model Exception - Stack Trace
java.lang.IllegalArgumentException: Type must either be DataSetIterator or DataSetIteratorFactory
at org.deeplearning4j.arbiter.scoring.util.ScoreUtil.getIterator(ScoreUtil.java:63)
at org.deeplearning4j.arbiter.task.ComputationGraphTaskCreator$GraphLearningTask.callHelper(ComputationGraphTaskCreator.java:113)
at org.deeplearning4j.arbiter.task.ComputationGraphTaskCreator$GraphLearningTask.call(ComputationGraphTaskCreator.java:87)
at org.deeplearning4j.arbiter.task.ComputationGraphTaskCreator$GraphLearningTask.call(ComputationGraphTaskCreator.java:63)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

#### Version Information
0.9.

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

You may try with this code by modifying at line 

MultiDataSetIterator dataSetIterator = ScoreUtil.getMultiIterator(dataProvider.trainData(candidate.getDataParameters()));

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/Arbiter/pull/117
