### ISSUE TITLE
OOM Error when training / seraching for hyperparameters

### ISSUE THREAD

**Issue by salamanders** [deeplearning4j/Arbiter#124]
#### Issue Description
I'm doing a hello-world test of hyperparameter tuning on a GPU, [see here](https://github.com/salamanders/deepworkout).  (I happen to be using Kotlin)
It works great for a few hours, then dies with a "failed to allocate device memory" error, which makes me think it might be a leak, instead of the model not fitting on the GPU.

I have a 4GB GPU.

    val hyperparamSpace = MultiLayerSpace.Builder()
        ...
    .build()
    val configuration = OptimizationConfiguration.Builder()
        .candidateGenerator(RandomSearchGenerator(hyperparamSpace, null))
        ....

which results in a few hours of success, then an error.

```
[ADSI prefetch thread] INFO org.deeplearning4j.datasets.iterator.MultipleEpochsIterator - Epoch 13, number of batches completed 938
[main] INFO org.deeplearning4j.arbiter.optimize.runner.BaseOptimizationRunner - Completed task 206, score = 0.9651
...
[ADSI prefetch thread] INFO org.deeplearning4j.datasets.iterator.MultipleEpochsIterator - Epoch 13, number of batches completed 938
Exception in thread "ADSI prefetch thread" java.lang.RuntimeException: java.lang.RuntimeException: Failed to allocate 10486784 bytes from DEVICE [0] memory
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$AsyncPrefetchThread.run(AsyncDataSetIterator.java:442)
Caused by: java.lang.RuntimeException: Failed to allocate 10486784 bytes from DEVICE [0] memory
	at org.nd4j.jita.memory.CudaMemoryManager.allocate(CudaMemoryManager.java:58)
	at org.nd4j.jita.workspace.CudaWorkspace.init(CudaWorkspace.java:69)
	at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.initializeWorkspace(Nd4jWorkspace.java:390)
	at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.close(Nd4jWorkspace.java:527)
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$AsyncPrefetchThread.run(AsyncDataSetIterator.java:421)
```

#### Version Information
* Deeplearning4j version: 0.9.1
* platform information (OS, etc): linux
* CUDA version, if used: `compile group: 'org.nd4j', name: 'nd4j-cuda-8.0-platform', version: "0.9.1"`
* NVIDIA driver version, if in use: 384.98

**Comment by agibsonccc** [comment]
I'm not convinced this is a memory leak so to speak. Some workloads just need more memory. You likely didn't set the memory properly.

http://deeplearning4j.org/memory - I am closing this.
