### ISSUE TITLE
CUDA memset exception - 

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/Arbiter#141]
Not sure if this is DL4J or Arbiter, but *probably* the latter.
Training proceeds fine, this occurs during evaluation. Note that the evaluation occurs in a listener, in the same thread as the network training...
After the exception occurs, all subsequent attempts at training a network fail.

```
o.d.o.l.PerformanceListener - Device: [1]; ETL: 0 ms; iteration 5500; iteration time: 184 ms; samples/sec: 347.826; batches/sec: 5.435;
o.d.o.l.PerformanceListener - Device: [1]; ETL: 0 ms; iteration 6000; iteration time: 183 ms; samples/sec: 349.727; batches/sec: 5.464;
i.s.o.ArbiterLocal - Starting evaluation for candidate 0
i.s.o.TrainLocal - --- Starting evaluation ---
CUDA error at /mnt/jenkins-slave-home/workspace/dl4j/all-multiplatform@3_linux-x86_64/stream2/libnd4j/blas/cuda/NativeOps.cu:4652 code=77(<unknown>) "result"
CUDA error at /mnt/jenkins-slave-home/workspace/dl4j/all-multiplatform@3_linux-x86_64/stream2/libnd4j/blas/cuda/NativeOps.cu:4652 code=77(<unknown>) "result"
i.s.o.ArbiterLocal - Error performing evaluation
org.nd4j.linalg.exception.ND4JIllegalStateException: CUDA stream synchronization failed
        at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:105)
        at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:94)
        at org.nd4j.jita.handler.impl.CudaZeroHandler.memcpy(CudaZeroHandler.java:734)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.memcpy(AtomicAllocator.java:955)
        at org.nd4j.jita.memory.CudaMemoryManager.memcpy(CudaMemoryManager.java:181)
        Suppressed: org.nd4j.linalg.exception.ND4JIllegalStateException: CUDA stream synchronization failed
                at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:105)
                at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:94)
                at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.flushQueueBlocking(CudaGridExecutioner.java:939)
                at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.commit(CudaGridExecutioner.java:1066)
                at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.close(Nd4jWorkspace.java:577)
o.d.a.t.ComputationGraphTaskCreator - Error in status listener for candidate 0
org.nd4j.linalg.exception.ND4JIllegalStateException: CUDA stream synchronization failed
        at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:105)
        at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:94)
        at org.nd4j.jita.handler.impl.CudaZeroHandler.memcpy(CudaZeroHandler.java:734)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.memcpy(AtomicAllocator.java:955)
        at org.nd4j.jita.memory.CudaMemoryManager.memcpy(CudaMemoryManager.java:181)
        Suppressed: org.nd4j.linalg.exception.ND4JIllegalStateException: CUDA stream synchronization failed
                at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:105)
                at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:94)
                at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.flushQueueBlocking(CudaGridExecutioner.java:939)
                at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.commit(CudaGridExecutioner.java:1066)
                at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.close(Nd4jWorkspace.java:577)
o.d.a.o.r.BaseOptimizationRunner - Completed task 0, score = 0.06267919260666871
o.d.a.o.r.BaseOptimizationRunner - New best score: 0.06267919260666871 (first completed model)
CUDA error at /mnt/jenkins-slave-home/workspace/dl4j/all-multiplatform@3_linux-x86_64/stream2/libnd4j/blas/cuda/NativeOps.cu:4633 code=77(<unknown>) "result"
o.d.a.t.ComputationGraphTaskCreator - Execution failed for task 1
org.nd4j.linalg.exception.ND4JIllegalStateException: memset failed device_1
        at org.nd4j.jita.workspace.CudaWorkspace.alloc(CudaWorkspace.java:158)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:451)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:396)
        at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:261)
        at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:64)
o.d.a.o.r.BaseOptimizationRunner - Task 1 failed during execution: org.nd4j.linalg.exception.ND4JIllegalStateException: memset failed device_1
        at org.nd4j.jita.workspace.CudaWorkspace.alloc(CudaWorkspace.java:158)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:451)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:396)
        at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:261)
        at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:64)
        at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createFloat(CudaDataBufferFactory.java:323)
        at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1476)
        at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1450)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:249)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:286)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:567)
        at org.nd4j.linalg.jcublas.JCublasNDArray.<init>(JCublasNDArray.java:254)
        at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:253)
        at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:5114)
        at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:5065)
        at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4170)
        at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:453)
        at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:378)
        at org.deeplearning4j.arbiter.task.ComputationGraphTaskCreator$GraphLearningTask.callHelper(ComputationGraphTaskCreator.java:145)
        at org.deeplearning4j.arbiter.task.ComputationGraphTaskCreator$GraphLearningTask.call(ComputationGraphTaskCreator.java:114)
        at org.deeplearning4j.arbiter.task.ComputationGraphTaskCreator$GraphLearningTask.call(ComputationGraphTaskCreator.java:84)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

CUDA error at /mnt/jenkins-slave-home/workspace/dl4j/all-multiplatform@3_linux-x86_64/stream2/libnd4j/blas/cuda/NativeOps.cu:4633 code=77(<unknown>) "result"
o.d.a.t.ComputationGraphTaskCreator - Execution failed for task 2
org.nd4j.linalg.exception.ND4JIllegalStateException: memset failed device_1
        at org.nd4j.jita.workspace.CudaWorkspace.alloc(CudaWorkspace.java:158)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:451)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:396)
        at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:261)
        at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:64)
o.d.a.o.r.BaseOptimizationRunner - Task 2 failed during execution: org.nd4j.linalg.exception.ND4JIllegalStateException: memset failed device_1
        at org.nd4j.jita.workspace.CudaWorkspace.alloc(CudaWorkspace.java:158)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:451)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:396)
        at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:261)
        at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:64)
        at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createFloat(CudaDataBufferFactory.java:323)
        at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1476)
        at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1450)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:249)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:286)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:567)
        at org.nd4j.linalg.jcublas.JCublasNDArray.<init>(JCublasNDArray.java:254)
        at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:253)
        at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:5114)
        at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:5065)
        at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4170)
        at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:453)
        at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:378)
        at org.deeplearning4j.arbiter.task.ComputationGraphTaskCreator$GraphLearningTask.callHelper(ComputationGraphTaskCreator.java:145)
        at org.deeplearning4j.arbiter.task.ComputationGraphTaskCreator$GraphLearningTask.call(ComputationGraphTaskCreator.java:114)
        at org.deeplearning4j.arbiter.task.ComputationGraphTaskCreator$GraphLearningTask.call(ComputationGraphTaskCreator.java:84)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by AlexDBlack** [comment]
A more complete stack trace for the same bug:
```
i.s.o.TrainLocal - --- Starting evaluation ---
CUDA error at /mnt/jenkins-slave-home/workspace/dl4j/all-multiplatform@3_linux-x86_64/stream2/libnd4j/blas/cuda/NativeOps.cu:4652 code=77(<unknown>) "result"
CUDA error at /mnt/jenkins-slave-home/workspace/dl4j/all-multiplatform@3_linux-x86_64/stream2/libnd4j/blas/cuda/NativeOps.cu:4652 code=77(<unknown>) "result"
org.nd4j.linalg.exception.ND4JIllegalStateException: CUDA stream synchronization failed
        at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:105)
        at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:94)
        at org.nd4j.jita.handler.impl.CudaZeroHandler.memcpy(CudaZeroHandler.java:734)
        at org.nd4j.jita.allocator.impl.AtomicAllocator.memcpy(AtomicAllocator.java:955)
        at org.nd4j.jita.memory.CudaMemoryManager.memcpy(CudaMemoryManager.java:181)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.migrate(BaseNDArray.java:5526)
        at org.deeplearning4j.nn.layers.AbstractLayer.migrateInput(AbstractLayer.java:111)
        at org.deeplearning4j.nn.layers.recurrent.BidirectionalLayer.migrateInput(BidirectionalLayer.java:509)
        at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.migrateInput(LayerVertex.java:272)
        at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:1644)
        at org.deeplearning4j.nn.graph.ComputationGraph.feedForward(ComputationGraph.java:1561)
        at org.deeplearning4j.nn.graph.ComputationGraph.silentOutput(ComputationGraph.java:1830)
        at org.deeplearning4j.nn.graph.ComputationGraph.doEvaluation(ComputationGraph.java:3460)
        at org.deeplearning4j.nn.graph.ComputationGraph.doEvaluation(ComputationGraph.java:3400)
        at io.skymind.orange.TrainLocal.evaluate(TrainLocal.java:122)
        at io.skymind.orange.ArbiterLocal$EvalListener.onCandidateStatusChange(ArbiterLocal.java:228)
        at org.deeplearning4j.arbiter.task.ComputationGraphTaskCreator$GraphLearningTask.call(ComputationGraphTaskCreator.java:120)
        at org.deeplearning4j.arbiter.task.ComputationGraphTaskCreator$GraphLearningTask.call(ComputationGraphTaskCreator.java:84)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: org.nd4j.linalg.exception.ND4JIllegalStateException: CUDA stream synchronization failed
                at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:105)
                at org.nd4j.linalg.jcublas.context.CudaContext.syncOldStream(CudaContext.java:94)
                at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.flushQueueBlocking(CudaGridExecutioner.java:939)
                at org.nd4j.linalg.jcublas.ops.executioner.CudaGridExecutioner.commit(CudaGridExecutioner.java:1066)
                at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.close(Nd4jWorkspace.java:577)
                at org.deeplearning4j.nn.graph.ComputationGraph.doEvaluation(ComputationGraph.java:3506)
                ... 9 more
```

**Comment by AlexDBlack** [comment]
Probably fixed here, need to re-run to confirm: https://github.com/deeplearning4j/deeplearning4j/pull/4671

**Comment by AlexDBlack** [comment]
Confirmed fixed here: https://github.com/deeplearning4j/libnd4j/pull/784
