### ISSUE TITLE
OutOfMemoryError: Physical memory usage is too high

### ISSUE THREAD

**Issue by lacic** [deeplearning4j/Arbiter#50]
Hi,

Running the [Arbiter example](https://github.com/deeplearning4j/dl4j-examples/blob/d66249548e1b836b9ce6e996e74f10dc63595f74/arbiter-examples/src/main/java/org/deeplearning4j/examples/arbiter/BasicHyperparameterOptimizationExample.java) in a for loop (and not calling System.exit) can cause an "OutOfMemoryError: Physical memory usage is too high" Exception.

I've tried to find a model/configuration for a RNN-LSTM for different datasets. The datasets are iterated within a for loop and for each dataset an Arbiter Example is run for 720 minutes.

The process is started with the -Xmx10g and -Xms10g JVM flags.

The first iteration finishes without any errors:

`INFO  [2016-12-12 19:11:49,311] org.deeplearning4j.arbiter.optimize.runner.BaseOptimizationRunner: BaseOptimizationRunner global termination condition hit: MaxTimeCondition(720,MINUTES,start="2016-12-12 07:11:48.713 UTC",end="2016-12-12 19:11:48.713 UTC")`

`Best score: 0.24872861780486183`
`Index of model with best score: 22`
`Number of configurations evaluated: 75`

`INFO  [2016-12-12 19:11:49,386] org.deeplearning4j.arbiter.optimize.runner.BaseOptimizationRunner: Optimization runner: execution complete
INFO  [2016-12-12 19:11:49,386] org.deeplearning4j.arbiter.optimize.runner.listener.runner.LoggingOptimizationRunnerStatusListener: Optimization runner: shutting down.`

But the second iteration produces then an OutOfMemoryError. Here is the [stack trace](https://gist.github.com/lacic/a626a965e3daa35e5af2811e8ba55bda)

Here are also the screen shots of the Java VisualVM while re-runing Arbiter with a MaxTimeCondition of 1 minute (-Xmx4G):

[arbiter_error_threads](https://postimg.org/image/toymk2qvd/)
[arbiter_error_monitor](https://postimg.org/image/d2h2azxxl/)
[arbiter_error_profiler](https://postimg.org/image/w8u9e6efd/)

And here is the profiler just moments before the error happens: [arbiter-error-profiler-before-exception](https://postimg.org/image/vzichwa47/)

**Comment by saudet** [comment]
Garbage collection isn't an exact science, especially for native resources. You could try to experiment by increasing the http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/Pointer.html#maxRetries value and by trying other garbage collectors such as `-XX:+UseG1GC -XX:MaxGCPauseMillis=100` or 
`-XX:+UseConcMarkSweepGC`. If that all fails though, please let me know. Thanks!

**Comment by lacic** [comment]
I've tried it out with both garbage collector options but neither does actually solve the problem.

Passing "-XX:+UseG1GC -XX:MaxGCPauseMillis=100" to the JVM and increasing maxRetries (tried with up to 60) is the better solution thou. Actually it does not solve it, but rather postpones the error - depending on how long a single arbiter instance is running (e.g., 10 sec, 30 sec, 1 min, 10 min, etc.) and how many iterations there are. 

I find it odd that even as the -Xmx flag is set to 4 GB, the complete remaining RAM is been used up.

For example, I've started the test on my PC with 7 GB of RAM used and having 8.4 GB free.
As seen in this [screen shot](https://postimg.org/image/5ur5hycm9/), while the heap space still looks fine., over time the whole remaining memory will be used.

**Comment by saudet** [comment]
Ok, could you provide the "loop" that you are using to reproduce that? And does it occur with MNIST or only with some other dataset?

**Comment by lacic** [comment]
Hi,

it can be also simulated with the Arbiter MNIST example which is provided in the arbiter-example project.

Here is the [gist](https://gist.github.com/lacic/e38cd9297120bba637c638f95ca92852) of the "adapted" version.

In this example, a for loop which iterates 30 times over the same code was added, MaxTimeCondition(20, TimeUnit.SECONDS) was set and, UI was removed and, at the end an "if" to not get an IndexOutOfBound exception when no results were found (due to the small timeout) was added.

On my PC (started with around 4GB or RAM used, having 15.4 available at all, and an -Xmx4g flag) after the 12th iteration (around 4 min) I get the "java.lang.OutOfMemoryError: Physical memory usage is too high (7676452864 > Pointer.maxPhysicalBytes)" error.

As seen [here](https://postimg.org/image/coh5e8ijj/), before the error happens more then 4 GB or RAM was used up (around 8 GB).

**Comment by saudet** [comment]
I am unable to reproduce this issue without Arbiter, so fortunately it doesn't look like a problem related to JavaCPP. For now I was able to track it down to LocalOptimizationRunner. For some reason, each new instance leaks about 500 megs of memory (in the case of the MNIST example) that is neither accounted by the JVM nor JavaCPP, but still off heap it seems as it doesn't show up in Java's profiler. If I move `new LocalOptimizationRunner()` out of the loop, then everything is fine.

**Comment by mjakobus** [comment]
I don't know how exactly the native backend is handling memory chaching and reuse, but this issue might be related to an issue with native caching in the cuda backend.
The cuda backend can't reuse the gpu memory if the ndarrays have a different size than the ones for which the memory was the first time allocated. For me this leads in a Arbiter kind of scenario very fast to an out of device memory problem (which I already worked around by purging the cache).
Since in the Arbiter example from @lacic the hidden layer size always having a different size and thus in each iteration a ndarray of different size gets allocated it might be a similar problem.
For more informations see: [nd4j/#1506](https://github.com/deeplearning4j/nd4j/issues/1506)

**Comment by raver119** [comment]
No, there's no memory reuse in nd4j-native backend besides of shapes cache, but that cache for average training workload is somewhere around 15-25 shapes. Way below even CUDA's 48kb.

**Comment by siddharthBohra** [comment]
Hi,
I am running the word2VecSentimentRNN, where i train using the pretrained GoogleNews-vectors-negative300.bin model.

I got the following error,

Starting training
Exception in thread "AsyncIterator thread" java.lang.OutOfMemoryError: Cannot allocate new FloatPointer(300): totalBytes = 3G, physicalBytes = 7G
	at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:76)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:445)
	at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:57)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:238)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1307)
	at org.nd4j.compression.impl.NoOp.decompress(NoOp.java:44)
	at org.nd4j.compression.impl.AbstractCompressor.decompress(AbstractCompressor.java:60)
	at org.nd4j.storage.CompressedRamStorage.get(CompressedRamStorage.java:138)
	at org.deeplearning4j.models.word2vec.StaticWord2Vec.getWordVectorMatrix(StaticWord2Vec.java:188)
	at org.deeplearning4j.examples.recurrent.word2vecsentiment.SentimentExampleIterator.nextDataSet(SentimentExampleIterator.java:132)
	at org.deeplearning4j.examples.recurrent.word2vecsentiment.SentimentExampleIterator.next(SentimentExampleIterator.java:73)
	at org.deeplearning4j.examples.recurrent.word2vecsentiment.SentimentExampleIterator.next(SentimentExampleIterator.java:209)
	at org.deeplearning4j.examples.recurrent.word2vecsentiment.SentimentExampleIterator.next(SentimentExampleIterator.java:33)
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$IteratorRunnable.run(AsyncDataSetIterator.java:303)
Caused by: java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes = 7G > maxPhysicalBytes = 7G
	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:562)
	at org.bytedeco.javacpp.Pointer.init(Pointer.java:121)
	at org.bytedeco.javacpp.FloatPointer.allocateArray(Native Method)
	at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:68)
	... 13 more
Exception in thread "main" java.lang.IllegalStateException: Unexpected state occurred for AsyncDataSetIterator: runnable died or no data available
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.next(AsyncDataSetIterator.java:232)
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator.next(AsyncDataSetIterator.java:36)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1012)
	at org.deeplearning4j.examples.recurrent.word2vecsentiment.Word2VecSentimentRNN.main(Word2VecSentimentRNN.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

I have the following in my idea.exe.vmoptions.
-server
-Xms128m
-Xmx10000m
-XX:ReservedCodeCacheSize=240m
-XX:+UseConcMarkSweepGC
-XX:SoftRefLRUPolicyMSPerMB=50
-ea
-Dsun.io.useCanonCaches=false
-Djava.net.preferIPv4Stack=true
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-XX:+UseG1GC
-XX:MaxGCPauseMillis=100

OS: 64bit windows 7
RAM : 16GB.

Kindly help me to resolve the issue. Please.

**Comment by raver119** [comment]
Your question has nothing to do with arbiter.
