### ISSUE TITLE
More than one ParameterSpace with same range causes exception

### ISSUE THREAD

**Issue by marcel-93** [deeplearning4j/Arbiter#84]
@AlexDBlack
@agibsonccc
If you define and use more than one ParameterSpace with **same ranges** it will causes an exception.
```
ParameterSpace<Double> l1Hyperparam = new ContinuousParameterSpace(0.001, 0.1);
ParameterSpace<Double> l2Hyperparam = new ContinuousParameterSpace(0.001, 0.1);

MultiLayerSpace hyperparameterSpace = new MultiLayerSpace.Builder()
       ...
       .l1(l1Hyperparam)
       .l2(l2Hyperparam)
       ...
```

```
Exception in thread "main" java.lang.IllegalStateException: Cannot get value: ParameterSpace index has not been set
	at org.deeplearning4j.arbiter.optimize.parameter.continuous.ContinuousParameterSpace.getValue(ContinuousParameterSpace.java:73)
	at org.deeplearning4j.arbiter.optimize.parameter.continuous.ContinuousParameterSpace.getValue(ContinuousParameterSpace.java:40)
	at org.deeplearning4j.arbiter.BaseNetworkSpace.randomGlobalConf(BaseNetworkSpace.java:184)
	at org.deeplearning4j.arbiter.MultiLayerSpace.getValue(MultiLayerSpace.java:76)
	at org.deeplearning4j.arbiter.MultiLayerSpace.getValue(MultiLayerSpace.java:24)
	at org.deeplearning4j.arbiter.optimize.candidategenerator.RandomSearchGenerator.getCandidate(RandomSearchGenerator.java:57)
	at org.deeplearning4j.arbiter.optimize.runner.BaseOptimizationRunner.execute(BaseOptimizationRunner.java:146)
	at de.contenit.nn.workflow.WorkflowClassifier.runArbiter(WorkflowClassifier.java:433)
	at de.contenit.nn.workflow.WorkflowClassifier.main(WorkflowClassifier.java:266)

```

https://github.com/deeplearning4j/Arbiter/blob/66e2839041dc3a2213a2606f3027d9e5c72523f2/arbiter-deeplearning4j/src/main/java/org/deeplearning4j/arbiter/MultiLayerSpace.java#L53

CollectionUtils.getUnique seems to be the cause because it is doing unique via .equals(), whereas in this siutation we need doing  unique via ==

**Comment by AlexDBlack** [comment]
As noted in gitter: finding unique laves at the provided link (```List<ParameterSpace> list = CollectionUtils.getUnique(collectLeaves());```) should be done using == not .equals()

**Comment by AlexDBlack** [comment]
Fixed here: will close this once that is merged. https://github.com/deeplearning4j/Arbiter/pull/85

**Comment by marcel-93** [comment]
👍 Great job thx!
